# Generated by Django 4.0.5 on 2022-06-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='Emp_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Emp_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='contact',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='department',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='designation',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='doj',
            field=models.DateField(blank=True, null=True),
        ),
    ]
