# Generated by Django 4.0.5 on 2022-06-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_alter_employeedata_emp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='Emp_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
