# Generated by Django 4.0.5 on 2022-06-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_alter_employeedata_emp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='Emp_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
